export const tags = [
  { name: "נורה", categoryId: 1 },
  { name: "מנורה", categoryId: 1 },
  { name: "שקע", categoryId: 1 },
  { name: "מגהץ", categoryId: 1 },
  { name: "טפט", categoryId: 1 },
  { name: "מדף", categoryId: 1 },
  { name: "דלת", categoryId: 1 },
  { name: "צמיד", categoryId: 2 },
  { name: "שעון", categoryId: 2 },
  { name: "טבעת", categoryId: 2 },
  { name: "שרשרת", categoryId: 2 },
  { name: "עגילים", categoryId: 2 },
  { name: "טלוויזיה", categoryId: 3 },
  { name: "רמקול", categoryId: 3 },
  { name: "אוזניות", categoryId: 3 },
  { name: "סטרימר", categoryId: 3 },
  { name: "מסך מחשב", categoryId: 3 },
  { name: "קונסולה", categoryId: 3 },
  { name: "אייפון", categoryId: 4 },
  { name: "סמסונג", categoryId: 4 },
  { name: "שיאומי", categoryId: 4 },
  { name: "סוני", categoryId: 4 },
  { name: "כבל USB", categoryId: 4 },
  { name: "מטען", categoryId: 4 },
  { name: "דונגל", categoryId: 4 },
  { name: "כדורגל", categoryId: 5 },
  { name: "כדור", categoryId: 5 },
  { name: "מחבט", categoryId: 5 },
  { name: "מגרש", categoryId: 5 },
  { name: "גיטרה", categoryId: 5 },
  { name: "פסנתר", categoryId: 5 },
  { name: "מחשב נייד", categoryId: 6 },
  { name: "מקלדת", categoryId: 6 },
  { name: "עכבר", categoryId: 6 },
  { name: "מדפסת", categoryId: 6 },
  { name: "מחברת", categoryId: 6 },
  { name: "עט", categoryId: 6 },
  { name: "ספה", categoryId: 7 },
  { name: "שולחן", categoryId: 7 },
  { name: "כיסא", categoryId: 7 },
  { name: "אדנית", categoryId: 7 },
  { name: "חוליה", categoryId: 7 },
  { name: "תיק", categoryId: 8 },
  { name: "ארנק", categoryId: 8 },
  { name: "חגורה", categoryId: 8 },
  { name: "משקפיים", categoryId: 8 },
  { name: "מקרר", categoryId: 9 },
  { name: "מכונת כביסה", categoryId: 9 },
  { name: "מייבש", categoryId: 9 },
  { name: "טלוויזיה לבית", categoryId: 9 },
  { name: "מיקסר", categoryId: 9 },
  { name: "סניקרס", categoryId: 10 },
  { name: "מגפיים", categoryId: 10 },
  { name: "נעלי ספורט", categoryId: 10 },
  { name: "נעלי עקב", categoryId: 10 },
  { name: "שמן זית", categoryId: 12 },
  { name: "קרם פנים", categoryId: 12 },
  { name: "שמפו", categoryId: 12 },
  { name: "איפור", categoryId: 12 },
  { name: "עגלה", categoryId: 13 },
  { name: "חיתולים", categoryId: 13 },
  { name: "בגד גוף", categoryId: 13 },
  { name: "צעצוע", categoryId: 13 },
  { name: "פאזל", categoryId: 14 },
  { name: "לגו", categoryId: 14 },
  { name: "משחק קופסה", categoryId: 14 },
  { name: "תחפושת", categoryId: 15 },
  { name: "כובע", categoryId: 15 },
  { name: "שמלה", categoryId: 15 },
  { name: "פאה", categoryId: 16 },
  { name: "סיכה", categoryId: 16 },
  { name: "סלסול", categoryId: 16 },
  { name: "כלב", categoryId: 17 },
  { name: "חתול", categoryId: 17 },
  { name: "אוכל חיות", categoryId: 17 },
  { name: "צימוד", categoryId: 17 },
  { name: "מצלמה", categoryId: 18 },
  { name: "אזעקה", categoryId: 18 },
  { name: "מנעול", categoryId: 18 },
  { name: "דלת בטחון", categoryId: 18 },
  { name: "iPhone", categoryId: 4 },
  { name: "Samsung", categoryId: 4 },
  { name: "Xiaomi", categoryId: 4 },
  { name: "MacBook", categoryId: 6 },
  { name: "Lenovo", categoryId: 6 },
  { name: "Nike", categoryId: 10 },
  { name: "Adidas", categoryId: 10 },
  { name: "Sony", categoryId: 3 },
  { name: "PlayStation", categoryId: 3 },
  { name: "Xbox", categoryId: 3 },
  { name: "Canon", categoryId: 3 },
  { name: "Dell", categoryId: 6 },
  { name: "HP", categoryId: 6 },
  { name: "LG", categoryId: 3 },
  { name: "Garmin", categoryId: 5 },
  { name: "Fitbit", categoryId: 5 },
  { name: "Samsung Gear", categoryId: 4 },
  { name: "Huawei", categoryId: 4 },
  { name: "Reebok", categoryId: 10 },
  { name: "Puma", categoryId: 10 },
  { name: "LEGO", categoryId: 14 },
  { name: "Fisher Price", categoryId: 14 },
  { name: "Play-Doh", categoryId: 14 },
  { name: "Crayola", categoryId: 14 },
  { name: "Dyson", categoryId: 9 },
  { name: "Bosch", categoryId: 9 }
];

export function searchTags(query) {
  if (!query) return [];
  const lowerQuery = query.toLowerCase();
  return tags.filter(tag => tag.name.toLowerCase().includes(lowerQuery));
}
